name: tonaparser
version: "0.1.0.0"
category: "Library, System, Tonatona"
synopsis: Scalable way to pass runtime configurations for tonatona
description:
  Tonaparser provides a way to pass runtime configurations.
  This library is supposed to be used with @tonatona@.
license: "MIT"
author: "Kadzuya Okamoto, Dennis Gosnell"
copyright: "2018 Kadzuya Okamoto"
maintainer: "arow.okamoto+github@gmail.com"

extra-source-files:
  - README.md

flags:
  buildexample:
    description: Build a small example program
    default: False
    manual: False

ghc-options: -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - envy >= 1.5
  - rio >= 0.1
  - say >= 0.1

library:
  source-dirs:
    - src
  exposed-modules:
    - TonaParser

executables:
  tonaparser-example:
    source-dirs:
      - example
    main: "Main.hs"
    dependencies:
      - say
      - tonaparser
    when:
      - condition: flag(buildexample)
        then:
          buildable: True
        else:
          buildable: False

tests:
  spec:
    main: "Spec.hs"
    other-modules: []
    source-dirs:
      - test
    dependencies:
      - tonatona
  doctest:
    main: "DocTest.hs"
    other-modules: []
    source-dirs:
      - test
    dependencies:
      - doctest
      - Glob

github: tonatona-project/tonatona
