name: tonatona-persistent-postgresql
version: "0.2.0.0"
category: "Database, Library, Tonatona"
synopsis: tonatona plugin for accessing PostgreSQL database.
description:
  Tonatona plugin for accessing PostgreSQL database.
  This package provides a tonatona plugin for accessing PostgreSQL database. This plugin uses persistent to actually accessing PostgreSQL.
license: "MIT"
author: "Kadzuya Okamoto, Dennis Gosnell"
copyright: "2018 Kadzuya Okamoto"
maintainer: "arow.okamoto+github@gmail.com"

tested-with: GHC==9.4.6, GHC==9.2.8, GHC==9.0.2, GHC==8.10.7

extra-source-files:
  - README.md

custom-setup:
  dependencies:
    - base >= 4.14 && < 4.18
    - Cabal < 3.12
    - cabal-doctest >= 1 && <1.1
    - rio >= 0.1 && < 0.2

ghc-options: -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.14 && < 4.18
  - rio >= 0.1 && < 0.2
  - monad-logger >= 0.3 && < 0.4
  - persistent >= 2.13 && < 2.15
  - persistent-postgresql >= 2.13 && < 2.14
  - resource-pool >= 0.2 && < 0.5
  - tonaparser >= 0.2 && < 0.3
  - tonatona >= 0.2 && < 0.3

library:
  source-dirs:
    - src
  exposed-modules:
    - Tonatona.Persist.Postgresql

tests:
  spec:
    main: "Spec.hs"
    other-modules: []
    source-dirs:
      - test
    dependencies:
      - tonatona
  doctests:
    main: "doctests.hs"
    other-modules: []
    source-dirs:
      - test
    dependencies:
      - doctest

github: tonatona-project/tonatona
