resolver: lts-21.8
packages:
  - .
  - ../tonalude
  - ../tonaparser
  - ../tonatona
  - ../tonatona-logger
  - ../tonatona-persistent-postgresql
  - ../tonatona-persistent-sqlite
  - ../tonatona-servant

flags: {}
extra-package-dbs: []
